server:
  port: 10001

spring:
  application:
    name: AI Assistant
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:NONE}
      base-url: ${OPENAI_BASE_URL:NONE}
      chat:
        options:
          model: DeepSeek-V3
        completions-path: /v1/chat/completions
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
          redis:
            key-prefix: "my_chat_memory:"
            time-to-live: "7d"
  data:
    redis:
      host: "localhost"
      port: 6379
      database: 0
      # username:
      # password:
      connect-timeout: 30s
      timeout: 30s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 10
          max-active: 20
          max-wait: -1ms
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver